version: '3'
services:

  db_web:
    container_name: db_web
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 112233
      POSTGRES_USER: admin
      POSTGRES_DB: db_web
    networks:
      - nw_db_web
      
    volumes:
      - "vl_web_data:/var/lib/postgresql/data"

  service_web:
    container_name: service_web
    restart: always
    build: ./web/
    ports:
     - "8000:8000"
    volumes:
      - ./web:/usr/src/app
    networks:
      - nw_db_web

    command: >
      bash -c "
        find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
        find . -path "*/migrations/*.pyc"  -delete
        python manage.py makemigrations myapp && 
        python manage.py migrate && 
        #python manage.py loaddata myapp/fixtures/* &&
        python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db_web

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8004:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=112233
    networks:
      - nw_db_web


networks:
  nw_db_web:

volumes:
  vl_web_data: